<?php
/*
*  Enqueue Scripts
*/
function ion_scripts() {
    wp_enqueue_style( 'googlefonts', 'https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700');
    wp_enqueue_style( 'bootstrap', get_template_directory_uri() . '/node_modules/bootstrap/dist/css/bootstrap.min.css' );
    wp_enqueue_style( 'slickcss', get_template_directory_uri() . '/node_modules/slick-carousel/slick/slick.css' );
    wp_enqueue_style( 'slicktheme', get_template_directory_uri() . '/node_modules/slick-carousel/slick/slick-theme.css' );
    wp_enqueue_style( 'style', get_stylesheet_uri() );

    wp_enqueue_script( 'slickjs', get_template_directory_uri()  . '/node_modules/slick-carousel/slick/slick.min.js', array(), '1.0.0', true );
    wp_enqueue_script( 'main', get_template_directory_uri() . '/js/main.js', array(), '1.0.0', true );
}
add_action( 'wp_enqueue_scripts', 'ion_scripts' );

/*
*  Register Nav Menus
*/
register_nav_menus( array(
	'main_menu' => 'Main Menu',
	'footer_menu' => 'Footer Menu',
) );

/*
*  Add Post Thumbnails
*/
add_theme_support( 'post-thumbnails' ); 
set_post_thumbnail_size( 150, 150, true );
add_image_size( 'testimonial-avatar', 53, 53, array( 'left', 'top' ) );

/*
*  Register Sidebar
*/
function register_all_sidebars() {
    register_sidebar( array(
        'name' => __( 'Page Sidebar', 'page-sidebar' ),
        'id' => 'aside-1',
        'description' => __( 'Widgets in this area will be shown on all pages.', 'jdequipment' ),
        'before_widget' => '<div id="%1$s" class="widget %2$s">',
        'after_widget'  => '</div>',
        'before_title'  => '<h2 class="widgettitle">',
        'after_title'   => '</h2>',
    ) );
    register_sidebar( array(
        'name' => __( 'Post Sidebar', 'post-sidebar' ),
        'id' => 'aside-2',
        'description' => __( 'Widgets in this area will be shown on all posts.', 'jdequipment' ),
        'before_widget' => '<div id="%1$s" class="widget %2$s">',
        'after_widget'  => '</div>',
        'before_title'  => '<h2 class="widgettitle">',
        'after_title'   => '</h2>',
    ) );
}
add_action( 'widgets_init', 'register_all_sidebars' );

/*
*  Add New Post Types
*/
function add_new_post_types() {
    register_post_type( 'testimonials',
      array(
        'labels' => array(
          'name' => __( 'Testimonials' ),
          'singular_name' => __( 'Testimonial' )
        ),
        'public' => true,
        'has_archive' => false,
        'exclude_from_search' => true,
        'supports' => array( 'title', 'thumbnail', 'excerpt' )
      )
    );
  }
  add_action( 'init', 'add_new_post_types' );

/*
*  Add Company Meta Box
*/
/**
 * Generated by the WordPress Meta Box generator
 * at http://jeremyhixon.com/tool/wordpress-meta-box-generator/
 */

function company_get_meta( $value ) {
	global $post;

	$field = get_post_meta( $post->ID, $value, true );
	if ( ! empty( $field ) ) {
		return is_array( $field ) ? stripslashes_deep( $field ) : stripslashes( wp_kses_decode_entities( $field ) );
	} else {
		return false;
	}
}

function company_add_meta_box() {
	add_meta_box(
		'company-company',
		__( 'company', 'company' ),
		'company_html',
		'testimonials',
		'side',
		'high'
	);
}
add_action( 'add_meta_boxes', 'company_add_meta_box' );

function company_html( $post) {
	wp_nonce_field( '_company_nonce', 'company_nonce' ); ?>
	<p>
      <label for="company_add_company_below"><?php _e( 'Add company below', 'company' ); ?></label><br>
      <input type="text" name="company_add_company_below" id="company_add_company_below" value="<?php echo company_get_meta( 'company_add_company_below' ); ?>">
	</p><?php
}

function company_save( $post_id ) {
	if ( defined( 'DOING_AUTOSAVE' ) && DOING_AUTOSAVE ) return;
	if ( ! isset( $_POST['company_nonce'] ) || ! wp_verify_nonce( $_POST['company_nonce'], '_company_nonce' ) ) return;
	if ( ! current_user_can( 'edit_post', $post_id ) ) return;

	if ( isset( $_POST['company_add_company_below'] ) )
		update_post_meta( $post_id, 'company_add_company_below', esc_attr( $_POST['company_add_company_below'] ) );
}
add_action( 'save_post', 'company_save' );

/*Output company role*/
function testimonial_role() {
    echo company_get_meta( 'company_add_company_below' );
}

/*
*  Redirect CF7
*/
function redirect_cf7() { ?>
    <script type="text/javascript">
    document.addEventListener( 'wpcf7mailsent', function( event ) {
        var mainUrl = window.location.protocol + '//' + window.location.hostname;

        if ( '56' == event.detail.contactFormId ) { // Sends submissions on all unaccounted for forms to the contact thank you page
            location = mainUrl + '/contact-thank-you';
        } else if ( '57' == event.detail.contactFormId ) { // Sends submissions to the subscribe contact thank you page
            location = mainUrl + '/subscribe-thank-you';
        } else { // Sends submissions on all unaccounted for forms to the default(contact) thank you page
            location = mainUrl + '/contact-thank-you';
        }
    
    }, false );
    </script>
    <?php
    }
    add_action( 'wp_footer', 'redirect_cf7' );
?>